name: Tflint
description: "terraform tool"
author: Das Meta
branding:
  icon: globe
  color: purple
inputs:
  fetch-depth: 
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: 0
  path:
    description: "Path where will run checkov"
    required: false
    default: /
  repo-token:
    description: "Path where will run checkov"
    required: false
  terraform_version:
    description: "Terraform version used in this action"
    required: false
    default: 1.3.6

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Setup TFLint
      run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      shell: bash
      continue-on-error: true
    
    - name: Show version
      run: tflint --version
      shell: bash

    - name: Set working directory
      run: |
        cd ${{inputs.path}}
      shell: bash
      continue-on-error: true

    - name: Init TFLint
      id: tflint
      run: |
          tflint --enable-rule=terraform_unused_declarations | sed -E 's/^([[:space:]]+)([-+])/\2\1/g'  > results.txt
      shell: bash
      continue-on-error: true

    - name: Put Files in ENV Vars
      run: |
        RESULT=$(cat results.txt)
        echo "RESULT<<EOF" >> $GITHUB_ENV
        echo "$RESULT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Post to GitHub PR
      if: steps.tflint.outputs.exit_code != 0
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${{ inputs.repo-token }}
        allow-repeats: true
        repo-token-user-login: 'github-actions[bot]'
        message: |
            ## Output
            ```diff
            ${{ env.RESULT }}
            ```

