name: Tflint
description: "terraform tool"
author: Das Meta
branding:
  icon: globe
  color: purple
inputs:
  fetch-depth: 
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: 0
  path:
    description: "Path where will run checkov"
    required: false
    default: modules/dashboard
  repo-token:
    description: "Path where will run checkov"
    required: false
  terraform_version:
    description: "Terraform version used in this action"
    required: false
    default: 1.3.6

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Setup TFLint
      run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      shell: bash
    
    - name: Show version
      run: tflint --version
      shell: bash

    - name: Set working directory
      run: |
        cd ${{inputs.path}}
      shell: bash

    - name: Init TFLint
      id: tflint
      run: |
          tflint --enable-rule=terraform_unused_declarations | sed -E 's/^([[:space:]]+)([-+])/\2\1/g'  > results.txt
      shell: bash
      continue-on-error: true

    - name: Comment on PR
      if: steps.tflint.outputs.exit_code != 0
      uses: peter-evans/create-or-update-pull-request-comment@v1
      with:
        body: |
          TFLint results:
          ```
          $(cat results.txt)
          ```
        token: ${{ secrets.GITHUB_TOKEN }} 
